# Generated by Django 4.1.5 on 2023-01-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('ap', models.CharField(max_length=255, verbose_name='Apellido paterno')),
                ('am', models.CharField(max_length=255, verbose_name='Apellido materno')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso')),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Estatura')),
                ('cc', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Circunferencia de cintura')),
                ('telefono', models.CharField(max_length=20, verbose_name='Télefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email / Correo electronico')),
                ('pa', models.CharField(choices=[['problema1', 'Problema 1'], ['problema2', 'Problema 2'], ['problema3', 'Problema 3']], max_length=255, verbose_name='Problemas actuales')),
                ('af', models.CharField(choices=[['antecedente1', 'Antecedente 1'], ['antecedente2', 'Antecedente 2'], ['antecedente3', 'Antecedente 3']], max_length=255, verbose_name='Antecedentes familiares')),
                ('ea', models.BooleanField(verbose_name='Embarazo actual')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
