# Generated by Django 4.1.5 on 2023-01-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='af',
            field=models.CharField(choices=[['obesidad', 'Obesidad'], ['diabetes', 'Diabetes'], ['cancer', 'Cancer'], ['hipercolesterolemia', 'Hipercolesterolemia'], ['hipertrigliceridemia', 'Hipertrigliceridemia']], max_length=255, verbose_name='Antecedentes familiares'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pa',
            field=models.CharField(choices=[['diarrea', 'Diarrea'], ['gastritis', 'Gastritis'], ['estrenimiento', 'Estreñimiento'], ['ulceras', 'Ulceras'], ['nauseas', 'Nauseas'], ['vomito', 'Vomito'], ['pirosis', 'Pirosis'], ['colitis', 'Colitis']], max_length=255, verbose_name='Problemas actuales'),
        ),
    ]
