version: '3.7'

services:
  api:
    build: .
    command: python consultorio/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: on-failure
  db:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: on-failure  
volumes:
  pg_data:
    driver: local
  