[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --forwarded-allow-ips=\"*\" --pythonpath /code/consultorio consultorio.wsgi:application --workers=3 --threads=2 --limit-request-line 8190 --bind [\"0.0.0.0\"]"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10